"""
UsdcCbbtcSlipstreamBase Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import UsdcCbbtcSlipstreamBaseStrategy
except ImportError:  # pragma: no cover - supports direct module execution in tests
    from strategy import UsdcCbbtcSlipstreamBaseStrategy

__all__ = [
    "UsdcCbbtcSlipstreamBaseStrategy",
]
